workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: Demo App Connect
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.lrcgroup.demoApp"
        APPLE_TEAM_ID: "8XRRMA7H34"
        PRODUCT_NAME: "Demo App"
        VERSION_NUMBER: "1.0.0"
        BUILD_NUMBER: "1"
    scripts:
      - name: Create Flutter project & install dependencies
        script: |
          set -e

          # echo "🚀 Création du projet iOS Flutter..."
          # flutter create .

          echo "🧹 Nettoyage du projet Flutter..."
          flutter clean
          flutter pub get
      
      - name: Update version
        script: |
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          cd ..
          
          # Update Flutter version in pubspec.yaml
          sed -i '' "s/version: .*/version: $VERSION_NUMBER+$BUILD_NUMBER/" pubspec.yaml

      - name: Force iOS 15.0 and install pods
        script: |
          cd ios
      
          # Ajout dans le Podfile
          if ! grep -q "platform :ios, '15.0'" Podfile; then
            sed -i '' "1s/^/platform :ios, '15.0'\n/" Podfile
          fi
      
          # Fix Xcode project
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' Runner.xcodeproj/project.pbxproj
      
          # Fix AppFrameworkInfo.plist
          plutil -replace MinimumOSVersion -string "15.0" Flutter/AppFrameworkInfo.plist || true
      
          pod deintegrate
          pod install
          cd ..

      - name: Set up code signing settings
        script: |
          echo "🔐 Setting up code signing..."
          cd ios
          xcode-project use-profiles

          echo "Creating ExportOptions.plist..."
          cat > ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.lrcgroup.demoApp</key>
                  <string>Demo App Prof</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>8XRRMA7H34</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Build IPA
        script: |
          echo "📦 Building IPA with code signing..."
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - kaiserstyve2@gmail.com
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"